### ISSUE TITLE
Thêm sản phẩm messenger vào app

### ISSUE THREAD

**Issue by thuongsugar** [phonghoanggg/Se07-23.1#2]
mọi người thêm sản phẩm messenger vào app và Iên kết page facebook vào sản phẩm messenger

**Comment by hoanggphong** [comment]
là sao b nhỉ mình vẫn chưa hiểu lắm.

**Comment by hoanggphong** [comment]
b có thể giải thích hoặc đưa doc cho mình tham khảo với

**Comment by thuongsugar** [comment]
> b có thể giải thích hoặc đưa doc cho mình tham khảo với

[đây](https://developers.facebook.com/docs/messenger-platform/getting-started/sample-experience#setup) bạn vào và tìm đến phần **_Cấp quyền truy cập Messenger cho ứng dụng Facebook_**
