### ISSUE TITLE
Mình bị lỗi khi dùng nick fb khác test bot mà bot không phản hồi. Dùng nick tạo page test thì ok. Mn giúp mình với

### ISSUE THREAD

**Issue by hoanggphong** [phonghoanggg/Se07-23.1#3]

**Comment by thuongsugar** [comment]
theo tôi được biết thì ứng dụng phát triển của bạn cần có quyền **pages_messaging**  đây là [link](https://developers.facebook.com/docs/messenger-platform/getting-started/sample-experience) tôi đọc được, bạn tìm đến phần cuối của trang
