### ISSUE TITLE
Bắt đầu cuộc hội thoại

### ISSUE THREAD

**Issue by thuongsugar** [phonghoanggg/Se07-23.1#5]
Khi người dùng lần đầu tiên click vào button chat thì cuộc hội thoại sẽ hiển thị button **bắt đầu** , khi người dùng sẵn sàng và click vào button thì bot sẽ gửi lời chào và đưa ra các lựa chọn cho người dùng

**Comment by thuongsugar** [comment]
Phong làm có gì thắc mắc thì comment ở đây.

**Comment by hoanggphong** [comment]
Mn ơi mình có đổi pass fb. Giờ chạy lại xảy ra lỗi. Không biết việc đổi pass fb có ảnh hưởng gì đến con bot mình đang làm k nhỉ? Mn giúp mình với

**Comment by thuongsugar** [comment]
> Mn ơi mình có đổi pass fb. Giờ chạy lại xảy ra lỗi. Không biết việc đổi pass fb có ảnh hưởng gì đến con bot mình đang làm k nhỉ? Mn giúp mình với

việc đổi mật khẩu FB thì sẽ làm cho token của app dev bị hết hạn vậy nên nếu đổi mật khẩu FB thì phải vào lại app dev để tạo token mới rồi cập nhật lại biến môi trường

**Comment by hoanggphong** [comment]
à thế à mình fix được rồi
